<a href="https://colab.research.google.com/github/kabilan942/Natural-Language-Processing/blob/main/Legal%20Document%20Summarization/jaccard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install transformers==4.21.0
!pip install sentencepiece
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import nltk
!pip install rouge
nltk.download('punkt')
from rouge import Rouge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 45.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 104.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.8/199.8 KB 21.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 19.0 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
import pandas as pd
import numpy as np
import glob
import json
import os
import sys
from tqdm import tqdm
sys.path.insert(0, '../')
from sklearn.metrics.pairwise import cosine_similarity
import torch

In [ ]:
!pip install transformers==4.21.0
!pip install sentencepiece
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import nltk
!pip install rouge
nltk.download('punkt')
from rouge import Rouge
!pip install datasets
from datasets import Dataset, DatasetDict
!pip install rouge_score
!pip install datasets evaluate transformers[sentencepiece]
!pip install nltk
from nltk.tokenize import sent_tokenize
import pandas as pd
import numpy as np
import glob
import nltk
nltk.download('punkt')
from nltk import tokenize
from torch.utils.data import DataLoader, TensorDataset, random_split, RandomSampler, Dataset
import torch.nn.functional as F
import torch
import json
import random
import os
import sys
sys.path.insert(0, '../')
from IPython.display import display, HTML
import torch
from datasets import load_dataset, load_metric, Dataset
from transformers import LEDTokenizer, LEDForConditionalGeneration
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments
import evaluate
rouge_score = evaluate.load('rouge')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 48.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 KB 13.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 KB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 23.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 22.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 10.8 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24954 sha256=9fbd4731c996b383b3c1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


## Chunking - Jaccard


In [ ]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125942 sha256=b8b2eb7bd419591412e457407a431697600e2279e063c8bf7793df104f718871
  Stored in directory: /root/.cache/pip/wheels/71/67/06/162a3760c40d74dd40bc855d527008d26341c2b0ecf3e8e11f
Successfully built sentence-transformers


In [ ]:
# Loading Model and tokenizer

from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('sentence-transformers/bert-base-nli-mean-tokens')

In [ ]:
from sklearn.metrics import jaccard_score

def similarity_l_l(l1, l2):
    '''
    Function to find the most similar sentence in the document for each sentence in the summary
    input:  l1 - Summary sentences
            l2 - Document sentences
    returns a list of document sentence indexes for each sentence in the summary
    '''
    document_embeddings = sbert_model.encode(l1+l2)
    similarities = []
    for emb1 in document_embeddings:
      l = []
      for emb2 in document_embeddings:
        score = jaccard_score(emb1, emb2)
        l.append(score)
      similarities.append(l)

    result = []
    for i in range(len(l1)):
        vals = similarities[i]
        vals = vals[len(l1):]
        idx = np.argmax(vals)
        result.append(idx)
    return result

In [ ]:
def nest_sentencesV2(document,chunk_length):
    '''
    function to chunk a document
    input:  document           - Input document
            chunk_length        - chunk length
    output: list of chunks. Each chunk is a list of sentences.
    '''
    nested = []
    sent = []
    length = 0
    for sentence in nltk.sent_tokenize(document):
        length += len(sentence.split(" "))
        if length < chunk_length:
            sent.append(sentence)  # sentences appended to sent till chunk_length is reached
        else:
            nested.append(sent)  # once reached, append sent to nested and make sent=[] and go through rest of sentences
            sent = []
            sent.append(sentence)
            length = 0
    if len(sent)>0:  # when all sentences are over and the chunk of remaining sentences are appended to sent
        nested.append(sent)
    return nested

In [ ]:
def get_chunks_data_from_docV2(doc, summ):
    '''
    Function to generate chunks along with their summaries
    input:  doc - legal Document
            summ - Gold standard summary
    returns a list of chunks and their summaries
    '''
    chunk_summ_word_threshold = 35
    sentence_mapping = {}
    doc_sents = split_to_sentences(doc)
    summ_sents = split_to_sentences(summ)

    result = (similarity_l_l(summ_sents,doc_sents))

    for i in range(len(summ_sents)):
        sentence_mapping[doc_sents[result[i]]] = summ_sents[i]

    final_chunks = []
    final_summ = []
    for chunk in nest_sentencesV2(doc, 465):
        summ = ""
        for chunk_sent in chunk:
            if chunk_sent in sentence_mapping:
                summ = summ + sentence_mapping[chunk_sent]
        if len(summ.split(" ")) >= chunk_summ_word_threshold:
            final_chunks.append(" ".join(chunk))
            final_summ.append(summ)
    return final_chunks, final_summ

In [ ]:
def get_root_path():
    '''
    function to get root path of dataset
    change the path variable to the path of the dataset
    '''
    # path = "/home/pahelibhattacharya/Abhayv2/camera_ready/summarization/dataset"
    path = "/content/drive/MyDrive/Legal Data/Indian Legal Abs Ext/dataset/IN-Abs/Single/train/"
    return path

def get_summary_data():
    '''
    function to get names, documents, and summaries
    change the path variable to the path of the dataset
    '''

    path = get_root_path() + '/judgement'
    all_files = glob.glob(path + "/*.txt")
    data_source = []
    names = []
    for filename in all_files:
        with open(filename, 'r') as f:
            p = filename.rfind("/")
            names.append(filename[p+1:])
            a = f.read()
            data_source.append(a)
    path = get_root_path() + '/summary'
    all_files = glob.glob(path + "/*.txt")
    data_summary = []
    for filename in all_files:
        with open(filename, 'r') as f:
            a = f.read()
            l = len(a)
            data_summary.append(a)

    return names, data_source, data_summary

def split_to_sentences(para):
    sents = nltk.sent_tokenize(para)   # returns list of sentences from para
    return sents


In [ ]:
names, data_source, data_summary = get_summary_data()
print(len(names))
print(len(data_source))
print(len(data_summary))


20
20
20


In [ ]:
import pandas as pd
from tqdm import tqdm
training_chunks = []
training_summs = []
doc_id = []
for i in tqdm(range(len(data_source))):
    cks, summs = get_chunks_data_from_docV2(data_source[i],data_summary[i])
    training_chunks = training_chunks + cks
    training_summs = training_summs + summs
    for j in range(len(cks)):
      doc_id.append(names[i])
df = pd.DataFrame({'data':training_chunks,'summary':training_summs,'doc_id':doc_id})
df.to_excel('FD_jac_512_3_train.xlsx')


  0%|          | 0/20 [00:08<?, ?it/s]


ValueError: ignored

In [ ]:
doc,sum = data_source[0],data_summary[0]

In [ ]:
len(doc), len(sum)

(18759, 800)

In [ ]:
doc_sents = split_to_sentences(doc)
summ_sents = split_to_sentences(sum)
print(doc_sents)
print(summ_sents)

['Appeal No.', 'LXVI of 1949.', 'Appeal from the High Court of judicature, Bombay, in a reference under section 66 of the Indian Income tax Act, 1022.', 'K.M.', "Munshi (N. P. Nathvani, with him), for the appel lant. '", 'M.C.', 'Setalvad, Attorney General for India (H. J. Umrigar, with him), for the respondent.', '1950.', 'May 26.', 'The judgment of the Court was delivered by MEHR CHAND MAHAJAN J.', 'This is an appeal against a judgment of the High Court of Judicature at Bombay in an income tax matter and it raises the question whether munici pal property tax and urban immoveable property tax payable under the relevant Bombay Acts are allowable deductions under section 9 (1) (iv) of the Indian Income tax Act.', 'The assessee company is an investment company deriving its income from properties in the city of Bombay.', 'For the assessment year 1940 41 the net income of the assessee under the head "property" was computed by the Income tax Officer in the sum of Rs.', '6,21,764 after deduc

In [ ]:
len(doc_sents),len(summ_sents), len(summ_sents+doc_sents)

(132, 10, 142)

In [ ]:
emb1 = sbert_model.encode(s1)
emb2 = sbert_model.encode(s2)

In [ ]:
len(emb1[0])

768

In [ ]:
jaccard_score(emb1[0], emb2[0])

ValueError: ignored

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, cosine_distances


In [ ]:
jaccard_set(emb1[0], emb2[0])

0.0

In [ ]:
e = euclidean_distances(list(emb1[0].reshape(-1,1)), list(emb2[0].reshape(-1,1)))

In [ ]:
s1 = 'I am a boy. I am a good boy'
s2 = 'I am a girl'

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, cosine_similarity

def similarity_l_l(l1, l2, metric):
    '''
    Function to find the most similar sentence in the document for each sentence in the summary
    input:  l1 - Summary sentences
            l2 - Document sentences
    returns a list of document sentence indexes for each sentence in the summary
    '''
    document_embeddings = sbert_model.encode(l1+l2)
    if metric==3:
      similarities=euclidean_distances(document_embeddings)
      print('Euclidean similarity')
    elif metric==2:
      similarities=manhattan_distances(document_embeddings)
      print('Manhattan similarity')
    else:
      similarities=cosine_similarity(document_embeddings)
      print('Cosine similarity')
    result = []
    for i in range(len(l1)):
        vals = similarities[i]
        vals = vals[len(l1):]
        idx = np.argmax(vals)
        result.append(idx)
    return result

In [ ]:
doc_sents = split_to_sentences(s1)
summ_sents = split_to_sentences(s2)

In [ ]:
doc_sents

['I am a boy.', 'I am a good boy']

In [ ]:
document_embeddings = sbert_model.encode(doc_sents+summ_sents)


In [ ]:

euclidean_distances(document_embeddings)



array([[ 0.      , 13.74847 , 17.845972],
       [13.74847 ,  0.      , 18.437319],
       [17.845972, 18.437319,  0.      ]], dtype=float32)

In [ ]:
manhattan_distances(document_embeddings)


array([[  0.        , 297.72023505, 382.27956119],
       [297.72023505,   0.        , 408.47510027],
       [382.27956119, 408.47510027,   0.        ]])

In [ ]:
cosine_similarity(document_embeddings)

array([[0.9999999 , 0.6813324 , 0.44757667],
       [0.6813324 , 1.        , 0.43025905],
       [0.44757667, 0.43025905, 1.0000002 ]], dtype=float32)

In [ ]:
e

array([[1.75816059e-01, 4.01742846e-01, 1.82779431e+00, ...,
        4.35349256e-01, 1.54683530e-01, 7.06072152e-03],
       [1.67014688e-01, 4.10544217e-01, 1.83659565e+00, ...,
        4.44150627e-01, 1.45882159e-01, 1.74064934e-03],
       [1.87918103e+00, 1.30162203e+00, 1.24429345e-01, ...,
        1.26801574e+00, 1.85804844e+00, 1.71042562e+00],
       ...,
       [1.00509751e+00, 4.27538574e-01, 9.98512864e-01, ...,
        3.93932164e-01, 9.83964980e-01, 8.36342156e-01],
       [3.77202094e-01, 2.00356811e-01, 1.62640822e+00, ...,
        2.33963221e-01, 3.56069565e-01, 2.08446756e-01],
       [6.45080209e-03, 5.84009707e-01, 2.01006103e+00, ...,
        6.17616117e-01, 2.75833309e-02, 1.75206140e-01]], dtype=float32)

In [ ]:
len(e)

768

In [ ]:
len(e[0])

768

In [ ]:
euclidean_distances(list(emb1[0]), list(emb2[0]))

ValueError: ignored

In [ ]:
from sklearn.metrics import jaccard_score

def similarity_l_l(l1, l2):
    '''
    Function to find the most similar sentence in the document for each sentence in the summary
    input:  l1 - Summary sentences
            l2 - Document sentences
    returns a list of document sentence indexes for each sentence in the summary
    '''
    document_embeddings = sbert_model.encode(l1+l2)
    similarities = []
    for emb1 in document_embeddings:
      l = []
      for emb2 in document_embeddings:
        score = jaccard_score(emb1, emb2)
        l.append(score)
      similarities.append(l)

    result = []
    for i in range(len(l1)):
        vals = similarities[i]
        vals = vals[len(l1):]
        idx = np.argmax(vals)
        result.append(idx)
    return result

In [ ]:
def jaccard_set(list1, list2):
    """Define Jaccard Similarity function for two sets"""
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection) / union

In [ ]:
y_true[0]

array([0.2, 0.1, 0.1])

In [ ]:
y_pred[0]

array([0.2, 0.1, 0.1])

In [ ]:
jaccard_set(y_true[0], y_pred[0])

[0.2 0.1 0.1]
[0.2 0.1 0.1]
2
4
0.5


In [ ]:
y_true = np.array([[0.2, 0.1, 0.1],
                    [0.01, 0.051, 0.3]])
y_pred = np.array([[0.2, 0.1, 0.1],
                    [0.4, 0.4, 0.051]])
y_pred1 = np.array([[0.2, 0.1, 0.1],
                    [0.4, 0.4, 0.051]])

In [ ]:
document_embeddings = sbert_model.encode(summ_sents+doc_sents)

In [ ]:
document_embeddings

array([[-0.24049655,  0.50827116,  0.94674   , ..., -0.73429304,
        -0.7288728 ,  0.44384214],
       [-0.16516326, -0.4452434 ,  1.9494433 , ..., -0.57685846,
        -1.0918163 , -0.06027391],
       [-0.6685927 ,  0.3809293 ,  0.510361  , ...,  0.2297117 ,
        -0.54303396,  0.23598135],
       ...,
       [-0.18186115,  0.5863771 ,  0.5198969 , ...,  0.46873015,
        -0.8737612 , -0.49299702],
       [-0.15229475, -0.26115277,  1.9724712 , ..., -0.2808213 ,
        -0.8091335 , -0.07113399],
       [ 0.01490215, -0.3179705 ,  2.306113  , ...,  0.5404378 ,
        -0.43471533, -0.03846959]], dtype=float32)

In [ ]:
jaccard_score(document_embeddings[0],document_embeddings[0],average='macro')

ValueError: ignored

In [ ]:
similarities = []
for i in range(document_embeddings.shape[0]):
  l = []

  for j in range(document_embeddings.shape[0]):
    #score = jaccard_score(document_embeddings[i],document_embeddings[j])
    score = jaccard_set(document_embeddings[i],document_embeddings[j])
    l.append(score)
  similarities.append(l)

In [ ]:
similarities[0]

[1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [ ]:
len(similarities[0])

142

In [ ]:
# for test dataset

def get_root_path():
    '''
    function to get root path of dataset
    change the path variable to the path of the dataset
    '''
    path = "/content/drive/MyDrive/Legal Data/Indian Legal Abs Ext/dataset/IN-Abs/Single/test/"
    return path

def get_summary_data():
    '''
    function to get names, documents, and summaries
    change the path variable to the path of the dataset
    '''

    path = get_root_path() + '/judgement'
    all_files = glob.glob(path + "/*.txt")
    data_source = []
    names = []
    for filename in all_files:
        with open(filename, 'r') as f:
            p = filename.rfind("/")
            names.append(filename[p+1:])
            a = f.read()
            data_source.append(a)
    path = get_root_path() + '/summary'
    all_files = glob.glob(path + "/*.txt")
    data_summary = []
    for filename in all_files:
        with open(filename, 'r') as f:
            a = f.read()
            l = len(a)
            data_summary.append(a)

    return names, data_source, data_summary


In [ ]:
names, data_source, data_summary = get_summary_data()
print(len(names))
print(len(data_source))
print(len(data_summary))

In [ ]:
import pandas as pd
from tqdm import tqdm
training_chunks = []
training_summs = []
doc_id = []
for i in tqdm(range(len(data_source))):
    cks, summs = get_chunks_data_from_docV2(data_source[i],data_summary[i])
    training_chunks = training_chunks + cks
    training_summs = training_summs + summs
    for j in range(len(cks)):
      doc_id.append(names[i])
df = pd.DataFrame({'data':training_chunks,'summary':training_summs,'doc_id':doc_id})
df.to_excel('FD_jac_512_3_test.xlsx')


## Fine-tuning T5 using Jaccard Similarity


In [ ]:
filepath = 'FD_jac_512_3_train.xlsx'
df = pd.read_excel(filepath,usecols='B,C')

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
from sklearn.model_selection import train_test_split
train_df, valid_df = train_test_split(df, test_size=0.20,shuffle=False)

In [ ]:
train_df.shape,valid_df.shape

In [ ]:
valid_df.reset_index(inplace=True)
valid_df.drop('index',inplace=True,axis=1)

In [ ]:
valid_df.head()

In [ ]:
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(valid_df)

In [ ]:
train_dataset

In [ ]:
datasets = DatasetDict()
datasets['train'] = train_dataset.remove_columns('__index_level_0__')
datasets['valid'] = val_dataset

In [ ]:
datasets

In [ ]:
model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [ ]:
max_input_length = 512
max_target_length = 256

def preprocess_function(examples):
  # Reviews are first tokenized
  model_inputs = tokenizer(examples['data'], truncation=True, max_length=max_input_length)
  # tokenizer for the target (highlights)
  with tokenizer.as_target_tokenizer():
    labels = tokenizer(examples['summary'], truncation=True, max_length=max_target_length)
  # The inputs are first encoded, and then the labels ('highlights') are encoded as a separate column
  model_inputs['labels'] = labels['input_ids']
  return model_inputs

In [ ]:
tokenized_dataset = datasets.map(preprocess_function, batched=True)

In [ ]:
tokenized_dataset

In [ ]:
from transformers import AutoModelForSeq2SeqLM

# Seq2SeqLM: sequence-to-sequence language modeling head

model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")  # model_checkpoint = "t5-small"

In [ ]:
# parameters of Seq2SeqTrainingArguments
batch_size = 4
num_training_epochs = 15
logging_steps = len(tokenized_dataset["train"])//4
model_name = "t5-small-finetuned-jac-3"
model_dir = "/content/drive/MyDrive/Legal Data/Indian Legal Abs Ext/dataset/IN-Abs/fine-tuned_models/t5-small-finetuned-jac-3.h5"

args = Seq2SeqTrainingArguments(evaluation_strategy='steps',
                                learning_rate=5.6e-5,
                                per_device_train_batch_size=batch_size,
                                per_device_eval_batch_size=batch_size,
                                weight_decay=0.01,
                                eval_steps=2,
                                save_steps=2,
                                save_total_limit=3,
                                num_train_epochs=num_training_epochs,
                                predict_with_generate=True,
                                logging_steps=logging_steps,
                                output_dir="t5-small-finetuned-jac-3",
                                load_best_model_at_end=True,
                                metric_for_best_model='eval_loss',
                                greater_is_better=False,
                                push_to_hub=False)


In [ ]:
import evaluate
rouge_score = evaluate.load('rouge')
def compute_metric(eval_pred):
  predictions, labels = eval_pred
  # Decode generated summaries into text (summaries generated from the review_body)
  # batch_decode -> Returns List[str]; The list of decoded sentences; Convert a list of lists of token ids into a list of strings by calling decode.
  decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True) # skip_special_tokens - Whether or not to remove special tokens in the decoding.
  # Replace -100 in the labels as we can't decode them
  labels = np.where(labels!=-100, labels, tokenizer.pad_token_id)
  # Decode reference summaries into text ('review_title')
  decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
  # ROUGE expects a newline after each sentence
  # strip() method removes characters from both left and right based on the argument
  decoded_preds = ['\n'.join(sent_tokenize(pred.strip())) for pred in decoded_preds]
  decoded_labels = ['\n'.join(sent_tokenize(pred.strip())) for pred in decoded_labels]
  # Computing ROUGE score
  # Stemming is used to remove plurals and word suffixes such as (ing, ion, ment)
  result = rouge_score.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
  result = {key: value*100 for key, value in result.items()}
  return {k: round(v,4) for k, v in result.items()}

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

In [ ]:
datasets['train'].column_names, len(datasets['train'].column_names)

In [ ]:
tokenized_dataset = tokenized_dataset.remove_columns(datasets['train'].column_names)
tokenized_dataset['train'].column_names

In [ ]:
from transformers import EarlyStoppingCallback
# args = Seq2SeqTrainingArguments()
# model = AutoModelForSeq2SeqLM.from_pretrained('t5-small')
# tokenizer = AutoTokenizer.from_pretrained('t5-small')
trainer = Seq2SeqTrainer(model, args, train_dataset=tokenized_dataset["train"], eval_dataset=tokenized_dataset["valid"],
                         data_collator=data_collator, tokenizer=tokenizer, compute_metrics=compute_metric,
                         callbacks=[EarlyStoppingCallback(early_stopping_patience=2)])

In [ ]:
trainer.train()

In [ ]:
trainer.evaluate()

**Have to change path**

In [ ]:
model_dir = "/content/drive/MyDrive/Legal Data/Indian Legal Abs Ext/dataset/IN-Abs/fine-tuned_models/t5-small-finetuned-jac-3.h5"
trainer.save_model(model_dir)

##Validation of fine-tuned Model

In [ ]:
filepath = 'FD_jac_512_3_test.xlsx'
test_df = pd.read_excel(filepath,usecols='B,C')

In [ ]:
def model_load(checkpoint):
     #model loaded from Huggingface
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
#Model Details
    #print("tokenizer.model_max_length :",tokenizer.model_max_length )# max token inputted in model 1024
    #print(" max tokens excluding the special tokens",tokenizer.max_len_single_sentence )# max tokens for input in model 1022
    #print("num_special_tokens_to_add ",tokenizer.num_special_tokens_to_add() ) # special token needed by model 2
    return(tokenizer,model)


In [ ]:
def sum_generate(FileContent,tokenizer,model):
    inputs = tokenizer(FileContent, return_tensors="pt", max_length=1024, truncation=True) # max_length = 1024 since length exceed otherwise and goes out of index range; genrating inputs with chunks pt stands for pytorch
    output = model.generate(inputs['input_ids'])  # inputs generated many list of tensors, from which 'input_ids' is used for generate
    summ_generated=tokenizer.decode(output[0], skip_special_tokens=True)# decoding the output  # output[0] used sinced tensor is find in [[]]
    return(summ_generated)

In [ ]:
def rouge_score_ud(summaryContent,final_summ_gen):
    rouge = Rouge()
    result_rouge=rouge.get_scores(summaryContent, final_summ_gen, avg=True)
# Printing the final list
    return result_rouge

In [ ]:
# inputs to the model
if __name__ == "__main__":
  checkpoint = "t5-small"
  result_rouge_list = []
  for i in range(test_df.shape[0]):
    FileContent,summaryContent=test_df['data'][i], test_df['summary'][i]
    tokenizer,model=model_load(checkpoint)
    final_summ_gen=sum_generate(FileContent,tokenizer,model)
    result_rouge_list.append(rouge_score_ud(summaryContent,final_summ_gen))

In [ ]:
result_rouge_list

In [ ]:
len(result_rouge_list)

In [ ]:
agg_rouge_score = {'rouge-1':{'r':0,'p':0,'f':0},'rouge-2':{'r':0,'p':0,'f':0},
                   'rouge-l':{'r':0,'p':0,'f':0}}

for i in range(len(result_rouge_list)):
  for rouge_type in ['rouge-1','rouge-2','rouge-l']:
    for j in ['r','p','f']:
      agg_rouge_score[rouge_type][j]+=(result_rouge_list[i][rouge_type][j]/len(result_rouge_list))

print(agg_rouge_score)

In [ ]:
# inputs to the model
if __name__ == "__main__":
  checkpoint = "/content/drive/MyDrive/Legal Data/Indian Legal Abs Ext/dataset/IN-Abs/fine-tuned_models/t5-small-finetuned-jac-3.h5"
  result_rouge_list = []
  for i in range(test_df.shape[0]):
    FileContent,summaryContent=test_df['data'][i], test_df['summary'][i]
    tokenizer,model=model_load(checkpoint)
    final_summ_gen=sum_generate(FileContent,tokenizer,model)
    result_rouge_list.append(rouge_score_ud(summaryContent,final_summ_gen))

In [ ]:
result_rouge_list

In [ ]:
len(result_rouge_list)

In [ ]:
agg_rouge_score = {'rouge-1':{'r':0,'p':0,'f':0},'rouge-2':{'r':0,'p':0,'f':0},
                   'rouge-l':{'r':0,'p':0,'f':0}}

for i in range(len(result_rouge_list)):
  for rouge_type in ['rouge-1','rouge-2','rouge-l']:
    for j in ['r','p','f']:
      agg_rouge_score[rouge_type][j]+=(result_rouge_list[i][rouge_type][j]/len(result_rouge_list))

print(agg_rouge_score)